services:
  db:
    image: postgres:18.3
    container_name: quiznova-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - backend
  api:
    build:
      context: .
      dockerfile: src/QuizNova.Api/Dockerfile
    container_name: quiznova-api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=QuizNova;Username=admin;Password=Moamen@SQL123
      JwtSettings__Issuer: QuizNova.Api
      JwtSettings__Audience: QuizNova.Client
      JwtSettings__Secret: QuizNova-Development-Secret-Key-Change-This-2026
      JwtSettings__ExpiryMinutes: 7
      AppSettings__Cors__PolicyName: "AngularClient"
      AppSettings__Cors__AllowedOrigins__0: "http://localhost:4200"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://seq:5341/ingest/otlp/traces
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
    ports:
      - "8080:8080"
    networks:
      - frontend
      - backend

  client:
    build:
      context: ./src/QuizNova.Client
      dockerfile: Dockerfile.dev

    container_name: quiznova-client

    volumes:
      - ./src/QuizNova.Client:/app
      - /app/node_modules

    restart: unless-stopped

    depends_on:
      api:
        condition: service_started

    environment:
      NODE_ENV: Development
    ports:
      - "4200:4200"

    networks:
      - frontend
  seq:
    image: datalust/seq:latest
    volumes:
      - ./containers/seq:/data
    environment:
      ACCEPT_EULA: Y
      SEQ_FIRSTRUN_NOAUTHENTICATION: "true"
    container_name: quiznova-seq
    ports:
      - "5341:5341"
      - "8081:80"
    networks:
      - backend
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    networks:
      - backend
    volumes:
      - ./containers/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    container_name: quiznova-prometheus
    ports:
      - "9090:9090"
    depends_on:
      - api
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: quiznova-grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: P@ssw0rd
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    restart: unless-stopped

    networks:
      - backend
volumes:
  postgres_data:
  grafana-data:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
