FROM node:22-alpine

WORKDIR /workspace

EXPOSE 4200

COPY src/QuizNova.Client/package*.json ./src/QuizNova.Client/

RUN cd src/QuizNova.Client && npm ci

CMD ["sh", "-c", "cd src/QuizNova.Client && npm run ng -- serve --ssr --host 0.0.0.0 --port 4200"]