// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuizNova.Infrastructure.Data;

#nullable disable

namespace QuizNova.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260530162822_AddCourseStatus")]
    partial class AddCourseStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.Courses.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InstructorId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaximumMarks")
                        .HasColumnType("integer");

                    b.Property<int>("MinimumPassingMarks")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("Courses", (string)null);
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.Enrollments.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EnrolledOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId", "CourseId")
                        .IsUnique();

                    b.ToTable("Enrollments", (string)null);
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.QuizAttempts.Answers.Base.QuestionAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuizAttemptId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuizAttemptId");

                    b.HasIndex("StudentId");

                    b.ToTable("QuestionAnswers", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.QuizAttempts.QuizAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.HasIndex("StudentId");

                    b.ToTable("QuizAttempts", (string)null);
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.Quizzes.Questions.AutoGradedQuestions.Mcq.Choices.Choice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Choices", (string)null);
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.Quizzes.Questions.Base.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<int>("Marks")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("Questions", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.Quizzes.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Quizzes", (string)null);
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("UserRole")
                        .HasColumnType("integer")
                        .HasColumnName("Role");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("QuizNova.Infrastructure.Identity.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("QuizNova.Infrastructure.Identity.UserRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserRefreshTokens");
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.QuizAttempts.Answers.AutoGradedAnswers.AutoGradedAnswer", b =>
                {
                    b.HasBaseType("QuizNova.Domain.Entities.QuizAttempts.Answers.Base.QuestionAnswer");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.ToTable("AutoGradedAnswers", (string)null);
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.QuizAttempts.Answers.ManuallyGradedAnswers.ManuallyGradedAnswers", b =>
                {
                    b.HasBaseType("QuizNova.Domain.Entities.QuizAttempts.Answers.Base.QuestionAnswer");

                    b.Property<string>("Feedback")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("GradedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Score")
                        .HasColumnType("integer");

                    b.ToTable("ManuallyGradedAnswers", (string)null);
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.Quizzes.Questions.AutoGradedQuestions.Mcq.Mcq", b =>
                {
                    b.HasBaseType("QuizNova.Domain.Entities.Quizzes.Questions.Base.Question");

                    b.Property<Guid?>("CorrectChoiceId")
                        .HasColumnType("uuid");

                    b.HasIndex("CorrectChoiceId");

                    b.ToTable("MCQs", (string)null);
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.Quizzes.Questions.AutoGradedQuestions.TrueFalse.Tf", b =>
                {
                    b.HasBaseType("QuizNova.Domain.Entities.Quizzes.Questions.Base.Question");

                    b.Property<bool>("CorrectChoice")
                        .HasColumnType("boolean");

                    b.ToTable("Tfs", (string)null);
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.Quizzes.Questions.ManuallyGradedQuestions.ManuallyGradedQuestion<string>", b =>
                {
                    b.HasBaseType("QuizNova.Domain.Entities.Quizzes.Questions.Base.Question");

                    b.Property<int?>("Score")
                        .HasColumnType("integer");

                    b.ToTable("ManuallyGradedQuestions", (string)null);
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.Users.Admins.Admin", b =>
                {
                    b.HasBaseType("QuizNova.Domain.Entities.Users.User");

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.Users.Instructors.Instructor", b =>
                {
                    b.HasBaseType("QuizNova.Domain.Entities.Users.User");

                    b.ToTable("Instructors", (string)null);
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.Users.Student.Student", b =>
                {
                    b.HasBaseType("QuizNova.Domain.Entities.Users.User");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.QuizAttempts.Answers.AutoGradedAnswers.McqAnswer.McqAnswer", b =>
                {
                    b.HasBaseType("QuizNova.Domain.Entities.QuizAttempts.Answers.AutoGradedAnswers.AutoGradedAnswer");

                    b.Property<Guid?>("McqId")
                        .HasColumnType("uuid");

                    b.HasIndex("McqId");

                    b.ToTable("McqAnswers", (string)null);
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.QuizAttempts.Answers.AutoGradedAnswers.TrueFalseAnswer.TfAnswer", b =>
                {
                    b.HasBaseType("QuizNova.Domain.Entities.QuizAttempts.Answers.AutoGradedAnswers.AutoGradedAnswer");

                    b.Property<Guid?>("TfId")
                        .HasColumnType("uuid");

                    b.HasIndex("TfId");

                    b.ToTable("TfAnswers", (string)null);
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.QuizAttempts.Answers.ManuallyGradedAnswers.EssayAnswer.EssayAnswer", b =>
                {
                    b.HasBaseType("QuizNova.Domain.Entities.QuizAttempts.Answers.ManuallyGradedAnswers.ManuallyGradedAnswers");

                    b.Property<string>("StudentResponse")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.ToTable("EssayAnswers", (string)null);
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.Quizzes.Questions.ManuallyGradedQuestions.Essay", b =>
                {
                    b.HasBaseType("QuizNova.Domain.Entities.Quizzes.Questions.ManuallyGradedQuestions.ManuallyGradedQuestion<string>");

                    b.Property<string>("AnswerReference")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.ToTable("Essays", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("QuizNova.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("QuizNova.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizNova.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("QuizNova.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.Courses.Course", b =>
                {
                    b.HasOne("QuizNova.Domain.Entities.Users.Instructors.Instructor", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.Enrollments.Enrollment", b =>
                {
                    b.HasOne("QuizNova.Domain.Entities.Courses.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizNova.Domain.Entities.Users.Student.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.QuizAttempts.Answers.Base.QuestionAnswer", b =>
                {
                    b.HasOne("QuizNova.Domain.Entities.Quizzes.Questions.Base.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizNova.Domain.Entities.QuizAttempts.QuizAttempt", "QuizAttempt")
                        .WithMany("StudentAnswers")
                        .HasForeignKey("QuizAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizNova.Domain.Entities.Users.Student.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("QuizAttempt");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.QuizAttempts.QuizAttempt", b =>
                {
                    b.HasOne("QuizNova.Domain.Entities.Quizzes.Quiz", "Quiz")
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizNova.Domain.Entities.Users.Student.Student", "Student")
                        .WithMany("QuizAttempts")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.Quizzes.Questions.AutoGradedQuestions.Mcq.Choices.Choice", b =>
                {
                    b.HasOne("QuizNova.Domain.Entities.Quizzes.Questions.AutoGradedQuestions.Mcq.Mcq", null)
                        .WithMany("Choices")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizNova.Domain.Entities.Quizzes.Questions.Base.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.Quizzes.Questions.Base.Question", b =>
                {
                    b.HasOne("QuizNova.Domain.Entities.Quizzes.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.Quizzes.Quiz", b =>
                {
                    b.HasOne("QuizNova.Domain.Entities.Courses.Course", "Course")
                        .WithMany("Quizzes")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizNova.Domain.Entities.Users.Instructors.Instructor", "Instructor")
                        .WithMany("Quizzes")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.Users.User", b =>
                {
                    b.OwnsOne("QuizNova.Domain.Entities.Users.UserPersonalInformation.PersonalInformation", "PersonalInformation", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("Email");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Name");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("PhoneNumber");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("PersonalInformation")
                        .IsRequired();
                });

            modelBuilder.Entity("QuizNova.Infrastructure.Identity.UserRefreshToken", b =>
                {
                    b.HasOne("QuizNova.Infrastructure.Identity.AppUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.QuizAttempts.Answers.AutoGradedAnswers.AutoGradedAnswer", b =>
                {
                    b.HasOne("QuizNova.Domain.Entities.QuizAttempts.Answers.Base.QuestionAnswer", null)
                        .WithOne()
                        .HasForeignKey("QuizNova.Domain.Entities.QuizAttempts.Answers.AutoGradedAnswers.AutoGradedAnswer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.QuizAttempts.Answers.ManuallyGradedAnswers.ManuallyGradedAnswers", b =>
                {
                    b.HasOne("QuizNova.Domain.Entities.QuizAttempts.Answers.Base.QuestionAnswer", null)
                        .WithOne()
                        .HasForeignKey("QuizNova.Domain.Entities.QuizAttempts.Answers.ManuallyGradedAnswers.ManuallyGradedAnswers", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.Quizzes.Questions.AutoGradedQuestions.Mcq.Mcq", b =>
                {
                    b.HasOne("QuizNova.Domain.Entities.Quizzes.Questions.AutoGradedQuestions.Mcq.Choices.Choice", "CorrectChoice")
                        .WithMany()
                        .HasForeignKey("CorrectChoiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuizNova.Domain.Entities.Quizzes.Questions.Base.Question", null)
                        .WithOne()
                        .HasForeignKey("QuizNova.Domain.Entities.Quizzes.Questions.AutoGradedQuestions.Mcq.Mcq", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CorrectChoice");
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.Quizzes.Questions.AutoGradedQuestions.TrueFalse.Tf", b =>
                {
                    b.HasOne("QuizNova.Domain.Entities.Quizzes.Questions.Base.Question", null)
                        .WithOne()
                        .HasForeignKey("QuizNova.Domain.Entities.Quizzes.Questions.AutoGradedQuestions.TrueFalse.Tf", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.Quizzes.Questions.ManuallyGradedQuestions.ManuallyGradedQuestion<string>", b =>
                {
                    b.HasOne("QuizNova.Domain.Entities.Quizzes.Questions.Base.Question", null)
                        .WithOne()
                        .HasForeignKey("QuizNova.Domain.Entities.Quizzes.Questions.ManuallyGradedQuestions.ManuallyGradedQuestion<string>", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.Users.Admins.Admin", b =>
                {
                    b.HasOne("QuizNova.Domain.Entities.Users.User", null)
                        .WithOne()
                        .HasForeignKey("QuizNova.Domain.Entities.Users.Admins.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.Users.Instructors.Instructor", b =>
                {
                    b.HasOne("QuizNova.Domain.Entities.Users.User", null)
                        .WithOne()
                        .HasForeignKey("QuizNova.Domain.Entities.Users.Instructors.Instructor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.Users.Student.Student", b =>
                {
                    b.HasOne("QuizNova.Domain.Entities.Users.User", null)
                        .WithOne()
                        .HasForeignKey("QuizNova.Domain.Entities.Users.Student.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.QuizAttempts.Answers.AutoGradedAnswers.McqAnswer.McqAnswer", b =>
                {
                    b.HasOne("QuizNova.Domain.Entities.QuizAttempts.Answers.AutoGradedAnswers.AutoGradedAnswer", null)
                        .WithOne()
                        .HasForeignKey("QuizNova.Domain.Entities.QuizAttempts.Answers.AutoGradedAnswers.McqAnswer.McqAnswer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizNova.Domain.Entities.Quizzes.Questions.AutoGradedQuestions.Mcq.Mcq", "Mcq")
                        .WithMany()
                        .HasForeignKey("McqId");

                    b.Navigation("Mcq");
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.QuizAttempts.Answers.AutoGradedAnswers.TrueFalseAnswer.TfAnswer", b =>
                {
                    b.HasOne("QuizNova.Domain.Entities.QuizAttempts.Answers.AutoGradedAnswers.AutoGradedAnswer", null)
                        .WithOne()
                        .HasForeignKey("QuizNova.Domain.Entities.QuizAttempts.Answers.AutoGradedAnswers.TrueFalseAnswer.TfAnswer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizNova.Domain.Entities.Quizzes.Questions.AutoGradedQuestions.TrueFalse.Tf", "Tf")
                        .WithMany()
                        .HasForeignKey("TfId");

                    b.Navigation("Tf");
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.QuizAttempts.Answers.ManuallyGradedAnswers.EssayAnswer.EssayAnswer", b =>
                {
                    b.HasOne("QuizNova.Domain.Entities.QuizAttempts.Answers.ManuallyGradedAnswers.ManuallyGradedAnswers", null)
                        .WithOne()
                        .HasForeignKey("QuizNova.Domain.Entities.QuizAttempts.Answers.ManuallyGradedAnswers.EssayAnswer.EssayAnswer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.Quizzes.Questions.ManuallyGradedQuestions.Essay", b =>
                {
                    b.HasOne("QuizNova.Domain.Entities.Quizzes.Questions.ManuallyGradedQuestions.ManuallyGradedQuestion<string>", null)
                        .WithOne()
                        .HasForeignKey("QuizNova.Domain.Entities.Quizzes.Questions.ManuallyGradedQuestions.Essay", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.Courses.Course", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.QuizAttempts.QuizAttempt", b =>
                {
                    b.Navigation("StudentAnswers");
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.Quizzes.Quiz", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("QuizNova.Infrastructure.Identity.AppUser", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.Quizzes.Questions.AutoGradedQuestions.Mcq.Mcq", b =>
                {
                    b.Navigation("Choices");
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.Users.Instructors.Instructor", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("QuizNova.Domain.Entities.Users.Student.Student", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("QuizAttempts");
                });
#pragma warning restore 612, 618
        }
    }
}
